# Criando Rotas:

para criar recursos, podemos utilizar de uma constante:

```js
const create = router.post('/',(req, res, next) => {
  res.status(200).send();
});
```

Podemos ter a mesma rota para diferentes tipos de recursos. Manter as rotas parecidas para o metodos `CRUD`.
  * Devemos deixar a rota parada e chavear pelo método.

Nos parametros da requisição temos:

```js
const create = router.post('/',(req, res, next) => {
  res.status(200).send();
});
```
* ### Na entrada:
  - `req` - a requisição (endereçamento para uma url)
    + se quiser pegar o corpo da requisição podemos obter a partir de `req.body`
  - `res` - a resposta (a resposta para a url)
    + devemos ter uma resposta com código:
      * `200` - normalizado
      * `201` - creado
      * `400` - bad request
      * `401` - não atenticado
      * `403` - acesso negado
      * `500` - error interno
  - `next` - o contexto (processeguir a execução)

* ### Métodos:
    * `get` - obter informações
    * `post` - enviar informações
    * `delete` - deletar informações
    * `put` - atualizar informações


### @Example:

```js
// queremos pegar o corpo da requisição
const create = router.post('/',(req, res, next) => {
  res.status(201).send(req.body); // ele não consegue converter json do nada.
});

app.use('/products',create);
// temos que utilizar um bodyparse. O corpo da requisição por um json.
const bodyParser = require('body-parser');
```

Para poder converter a requisição do corpo:

```shell
npm install body-parse --save
```

precisamos falar que aplicação está usando o body-parser.

```js
app.use(bodyParser.json()); // todo o conteúdo vai ser convertido para json
app.use(bodyParser.urlencoded({ extended: false})); // codificar a url's (como por exemplo o espaço em branco)
```

tem outras opções no bodyParser.
 * Podemos determinar o tamanho máximo


<hr>

### Receber Parametros:

podemos receber um parametros da `url`:

```js
// receber um parametro - determinado produto
const put = router.put('/:id',(req, res, next) => {
  let id = req.params.id; // recuperar a forma da url.
  res.status(201).send({
    id: id,
    item: req.body
  });
});
```

<hr>

### Organizando:

vamos criar uma pasta dentro do src - de `routes`, um arquivo de routes. Deixamos uma rota com a raiz, toda a vez que chamamos a api.

```js
'use strict';

const express = require('express'); // para criar a rota
const router = express.Router();

router.get('/',(req, res, next) => {
  res.status(200).send({
    title: "Node Store Api",
    version: "0.0.2"
  });
}); //a mesma rota

module.exports = router;
```

no arquivo `app.js`

```js
// carrega as rotas
const index = require('./routes/index');
```
